name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run detekt
      run: ./gradlew detekt
    - name: Run tests
      run: ./gradlew test
    - name: Build jar
      run: ./gradlew shadowJar
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: jar
        path: build/libs/tracklin.jar
